# Generated by Django 5.1 on 2024-09-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Escrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_released", models.BooleanField(default=False)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
